import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "./SessionProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative overflow-x-hidden antialiased`}
      >
              <SessionProvider>
              {/* <div className="fixed top-3 z-50 right-0">
              <Image
                src="/logo.png"
                width={58} // Adjust width
                height={58} // Adjust height
                alt="Furnishing Hero"
                className="object-contain w-[50px] h-[50px] "
                priority
              />
            </div> */}
        {children}
        <Toaster />
              </SessionProvider>
      </body>
    </html>
  );
}
